### ISSUE TITLE
propress

### ISSUE THREAD

**Issue by mrzhangzizhen123** [xairc/lung_nodule_detector#6]
i have the difficulity when i run the prepare.py.please tell me how to solve the problem that some datas couldn't change the .npy. looking forward to your letter.

**Comment by dypark86** [comment]
can you show me the error message?
- see config_training.py for set data paths.
- or using https://github.com/xairc/lung_nodule_summary/prepare.py

thanks!

**Comment by mrzhangzizhen123** [comment]
The first epoch of our training network was 0.079. Is this a normal result of training?

**Comment by dypark86** [comment]
may be it takes about 1 or 2days.
