### ISSUE TITLE
hi，Ｉ　ｈａｖｅ　ａ　ｐｒｏｂｌｅｍ．ｔｈａｎｋ　ｙｏｕ　

### ISSUE THREAD

**Issue by mrzhangzizhen123** [xairc/lung_nodule_detector#7]
How do lun16 and lidc datasets work in code?What is the relationship between the two?

**Comment by dypark86** [comment]
lidc is dataset of lung nodule.
and luna16 is lung nodule competition with lidc dataset.

luna16 select some patient data of lidc dataset for except Problematic data.
and  in this project, we use luna 16 data for equitable measure with other luna16 competitor.

and lidc xml data has nodule annotation of malignancy and other attribute.
but this data not using in this project, some other my projects need this data.
so this project's prepare.py preprocess data with lidc xml data
